# version: "3.8"
# services:
#   redis:
#     image: redis
#     ports:
#       - "6379:6379"
#     command: redis-server

#   nextapp:
#     build: .
#     ports:
#       - "4000:3000"
#     depends_on:
#       - redis

version: "3.8"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - ./redis/data:/data # ./redis/data:/data表示将一个地址为 ./redis/data的 volume 挂载到 Redis 容器的 /data目录。

  nextapp:
    build: .
    ports:
      - "4000:3000"
    depends_on:
      - redis
